## Numpy
- Numerical Python
- C언어로 구현된 저수준의 고성능 라이브러리
- 빠르고 메모리 효율적으로 다차원 배열 ndarray 연산 지원
- 선형대수 난수 발생기, 푸리에 변환 등 다양한 연산 기능 지원

In [2]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


### numpy로 배열 만들기

In [26]:
# 0차원 배열 - 배열에 원소가 하나만 들어 있는 것
arr0D = np.array([39])
print(arr0D)
# 1차원 배열 - 하나의 행이나 열로 이루어진 배열
arr1D = np.array([1, 2, 3, 4])
print(arr1D)
# 2차원 배열 - 행과 열로 이루어진 배열
arr2D = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr2D)
# 3차원 배열 - 2차원 배열이 stack처럼 올라가있다고 생각하면 쉽다.
arr3D = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])                
print(arr3D)

[39]
[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


### 배열 초기화 하는 법

In [5]:
# 0으로 채워진 1차원 배열을 만들어 준다.
arr0Init = np.zeros(2)
print(arr0Init)
# 1로 채워진 1차원 배열을 만들어 준다.
arr1Init = np.ones(2)
print(arr1Init)
# 빈 배열을 만들어준다.
arrEmpty = np.empty(2)
print(arrEmpty)
# index와 value를 입력하면 index 갯수만큼 value를 가진 배열을 만들어준다.
arrFull = np.full(2, 5)
print(arrFull)
# nxn identity 행렬을 만들어 준다.
arrEye = np.eye(3)
print(arrEye)
# 랜덤값을 가진 행렬을 만들어 준다.
arrRan = np.random.random((2, 2))
print(arrRan)
# 원소의 범위만큼 1차원 배열을 만들어 준다.
# np.arange(start value, finish value, interval)
arrArange = np.arange(2, 9, 2)
print(arrArange)
#시작 값과 끝 값을 입력받은 숫자 만큼 나눈 배열을 만들어 준다.
arrLin = np.linspace(0, 35, num=8)
print(arrLin) 


[0. 0.]
[1. 1.]
[1. 1.]
[5 5]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.96656758 0.38521503]
 [0.23988835 0.78010792]]
[2 4 6 8]
[ 0.  5. 10. 15. 20. 25. 30. 35.]


### numpy array 데이터 타입 확인하기
- 'i' : integer
- 'b' : byte
- 'u' : unsigned integer
- 'f' : float
- 'c' : complex float
- 'm' : timedelta
- 'M' : datetime
- 'O' : object
- 'S' : string
- 'U' : unicode string
- 'V' : fixed chuck of memory for other type 

In [33]:
# 현재 들어있는 배열의 데이터 타입을 확인한다.
arr = np.array([1, 2, 3])
print(arr.dtype)
# 배열의 데이터 타입을 캐스팅하고 배열의 데이터 타입 출력하기
arr2 = np.array([4, 5, 6], dtype='f')
print(arr2)
print(arr2.dtype)
# 문자는 정수로 변환 될 수 없다.
# 배열의 데이터 타입을 변경하면서 복사해오기.
arr3 = np.array([1.1, 2.1, 3.1])
newArr = arr3.astype('i')
print(newArr)
print(newArr.dtype)
# 배열의 차원 즉 배열의 축의 갯수를 말해준다.
arrExp = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 21, 31], [41, 51, 61]], [[12, 22, 32], [42, 52, 62]]])
print(arrExp.ndim)
# 배열의 원소 갯수 알아내기
print(arrExp.size)
# 배열의 길이를 알아낸다. 여기서 길이는 일반적인 배열의 길이가 가 아닌 배열의 차원이다.
print(len(arrExp))
# shape는 (차원, 1차원의 행 갯수, 1차원의 열 갯수)
print(arrExp.shape)
# 3차원에서 배열값 찾아보기
print(arrExp[0, 1, 1])

int32
[4. 5. 6.]
float32
[1 2 3]
int32
3
18
3
(3, 2, 3)
5


### numpy array 형식 바꾸기

In [62]:
# array를 n행 m열로 기존의 배열을 변경한다.
a = np.arange(6)
b = a.reshape(3, 2)
print(b)
# n차원 배열을 1 차원으로 변경하는 것
c = b.reshape(-1)
print(c)
# array 슬라이싱하기 기존의 파이썬 문법과 똑같다
print(c[1])
print(c[0:2])
print(c[-2:])
print(c[1:4])
print(c[-3:-1])
# 2차원 배열 슬라이싱 하기. [행, 열]로 잘려서 나타난다.
print(b[0:3, 0])
# 2개의 배열 합치기
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)
# 배열을 stack형으로 쌓아갈 수 있음
arr = np.stack((arr1, arr2), axis=1)
print(arr)
# split으로 배열을 나눠 줄 수 있음
arr = np.array_split(c, 3)
print(arr)
# 배열을 복사한다. 하지만 복사한 배열과 복사돼서 새로 생긴 배열은 메모리를 같이 공유하지 않는다.
d = c.copy()
d[0] = 42
print(d)
# 배열의 원소를 검색하는 법
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
a = np.arange(15)
x = np.where((a >= 5) & (a <= 10))
print(a[x])
# 두 개의 1차원 배열을 비교해서 중복되는 게 있는 지 찾아보기
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d(a, b)
# 두 개의 배열 비교해서 중복되는 원소 제거하기.
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
np.setdiff1d(a, b)
# 배열 정렬하기
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
# 배열에서 중복되는 원소들을 하나로 출력시켜준다.
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
uniqueValues = np.unique(arr)
print(uniqueValues)

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]
1
[0 1]
[4 5]
[1 2 3]
[3 4]
[0 2 4]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[array([0, 1]), array([2, 3]), array([4, 5])]
[42  1  2  3  4  5]
(array([3, 5, 6], dtype=int64),)
[ 5  6  7  8  9 10]
[0 1 2 3]
[11 12 13 14 15 16 17 18 19 20]


### numpy array의 수학 연산자

In [66]:
# 더하기
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data + ones)
# 빼기 나누기 곱하기
print(data - ones)
print(data * ones)
print(data / data)

[2 3]
[0 1]
[1 2]
[1. 1.]


In [68]:
# Broadcasting - 배열에 숫자를 곱하는 것
data = np.array([1.0, 2.0])
print(data * 1.6)
# max, min, sum과 같이 유용한 함수들
print(data.max())
print(data.min())
print(data.sum())

[1.6 3.2]
2.0
1.0
3.0
